// <auto-generated />
using System;
using CaptchaTraining.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace CaptchaTraining.Migrations
{
    [DbContext(typeof(CaptchaDbContext))]
    [Migration("20211031213009_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("CaptchaTraining.Model.CaptchaDataSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Pictures")
                        .HasColumnType("text");

                    b.Property<bool>("hasAnswers")
                        .HasColumnType("boolean");

                    b.Property<bool>("hasCyrillic")
                        .HasColumnType("boolean");

                    b.Property<bool>("hasLatin")
                        .HasColumnType("boolean");

                    b.Property<bool>("hasNumeric")
                        .HasColumnType("boolean");

                    b.Property<bool>("hasSpecialSymbols")
                        .HasColumnType("boolean");

                    b.Property<bool>("isCaseSesitive")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("CaptchaDataSets");
                });
#pragma warning restore 612, 618
        }
    }
}
